# Generated by Django 3.2.7 on 2021-10-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=500, verbose_name='язык'),
        ),
    ]
